import ReactQueryProvider from '@/providers/reactQueryProvider';
import { ReactQueryDevtools } from '@tanstack/react-query-devtools';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ReactQueryProvider>
      {children}
      <ReactQueryDevtools
        initialIsOpen={false}
        position='left'
        buttonPosition='bottom-left'
      />
    </ReactQueryProvider>
  );
}
